A = #(48.742737+62.427467i)
B = #(60-40i)
C = #(-60-40i)
[orange] [fill] t = triangle(A, B, C)
[gray] c = incircle(t)
D = pole(A, B, c)
E = pole(A, C, c)
H = project(B, bisector(B, C, A))
[blue] segment(B, H)
[blue] segment(C, H)
[green] [fill] angle(A, C, H)
[green] [fill] angle(B, C, H)
[violet] [fill] angle(C, H, B)
[red] [dash] segment(D, E)
