A = #(20+60i)
B = #(60-40i)
C = #(-60-40i)
[orange] [fill] t = triangle(A, B, C)
[blue] c = circumcircle(t)
M = cintersect(A, exbisector(B, A, C), c)
[gray] [equal1] segment(B, M)
[gray] [equal1] segment(C, M)
X = choose(segment(A, B), time()/500)
[green] [equal2] l = segment(B, X)
Y = divide(length(l)/length(A, C), C, A)
[green] [equal2] segment(C, Y)
[dash] [red] circumcircle(M, X, Y)
